# Output file paths
output_paths:
  dir: "./output"
  summary: "./output/summary.md"
  study_guide: "./output/study_guide.md"
  quiz: "./output/quiz_questions.md"
  answers: "./output/quiz_answers.md"

# Task configurations
tasks:
  extract_info:
    description_template: |
      Your task is to extract key information from the following document:

      {source_content}

      Please extract:
      1. Key concepts and main ideas
      2. Supporting details and examples
      3. Technical terms and definitions
      4. Important relationships and connections between concepts
      5. Any numerical data or specific facts
      Organize the information by sections as they appear in the document.
    expected_output: |
      A dictionary containing extracted information with the following structure:
      {
        'main_concepts': [list of key concepts],
        'supporting_details': {concept: [related details]},
        'technical_terms': {term: definition},
        'relationships': [list of concept relationships],
        'facts': [list of important facts and data]
      }
    agent: extract_agent
    context: []  # No dependencies for initial extraction

  write_summary:
    description_template: |
      From document:
      {source_content}

      Create an integrated summary that serves as a foundation for the study guide and quiz.
      Structure the summary to:
      1. Begin with a concise overview (1-2 paragraphs) that introduces the main concepts
      2. Present key takeaways as actionable learning objectives
      3. Provide a detailed breakdown that:
         - Explains concepts in a logical progression
         - Integrates technical terms within their relevant context
         - Demonstrates relationships between concepts using practical examples
         - Weaves important facts naturally into the explanations
      4. Include transition sentences between sections
      5. Use clear visual hierarchy with appropriate headings and subheadings
      Format the summary in markdown starting with '# Summary' heading.
    expected_output: |
      A markdown formatted summary with clear hierarchy, integrated concepts, and smooth transitions 
      between sections. The summary should serve as a foundation for the study guide and quiz.
    agent: writer_agent
    output_file: "{output_paths.summary}"
    context: ["extract_info"]  # Depends on extracted information

  create_study_guide:
    description_template: |
      Create an integrated study guide that builds upon and references the summary.
      Structure the guide to:
      1. Begin with clear learning objectives that map to the summary's key takeaways
      2. For each major concept from the summary:
         - Provide detailed explanations with cross-references to the summary
         - Include practical examples that demonstrate concept applications
         - Highlight key terms in context with their relationships
         - Add study tips and common pitfalls to avoid
      3. Include visual elements (ASCII diagrams or structured lists) to illustrate relationships
      4. End each section with review prompts that prepare for the quiz
      Format the study guide in markdown starting with '# Study Guide' heading.
    expected_output: |
      A markdown formatted study guide that integrates with the summary, uses visual elements, 
      and prepares readers for the quiz through targeted review prompts.
    agent: writer_agent
    output_file: "{output_paths.study_guide}"
    context: ["extract_info", "write_summary"]  # Depends on both extraction and summary

  create_quiz:
    description_template: |
      Create an assessment quiz that directly ties to the summary and study guide.
      {quiz_config}

      Structure the quiz to:
      1. Begin with a brief introduction connecting it to the study guide's learning objectives
      2. Include a mix of questions that:
         - Progress from basic recall to complex application
         - Reference specific concepts from the summary
         - Test relationships and connections identified in the study guide
         - Include practical scenarios based on the examples provided
      3. Group questions by topic and complexity, not just by type
      4. Use clear formatting and numbering that aids navigation
      Format the quiz in markdown starting with '# Quiz Questions' heading.
    expected_output: |
      A markdown formatted quiz that integrates with the summary and study guide, featuring 
      progressive complexity and clear organization by topic.
    agent: writer_agent
    output_file: "{output_paths.quiz}"
    context: ["extract_info", "write_summary", "create_study_guide"]  # Depends on all previous tasks

  create_quiz_answers:
    description_template: |
      Create comprehensive answer explanations that reinforce learning objectives.
      Structure the answers to:
      1. Begin with a brief overview of the topics covered in the quiz
      2. For each answer:
         - Provide the correct response with detailed reasoning
         - Cross-reference relevant sections in the summary and study guide
         - Explain common misconceptions or incorrect answers
         - Include additional examples or scenarios for deeper understanding
      3. End with key learning points that tie back to the original objectives
      Format answers in markdown starting with '# Quiz Answers' heading.
    expected_output: |
      A markdown formatted answer key that reinforces learning through detailed explanations 
      and connections to the summary and study guide.
    agent: writer_agent
    output_file: "{output_paths.answers}"
    context: ["create_quiz"]  # Depends on quiz questions
